name: Deploy Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - 'feature/**'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --quiet

      - name: Lint
        run: npm run lint

      # TODO: Use in deploy of branches as key
      # - name: GitHub Refs
      #   if: contains(github.event.pull_request.labels.*.name, 'deploy')
      #   uses: rlespinasse/github-slug-action@v3.x

      # NOTE: the deploy can also use the secrets directly from the enviroment
      # so the configure-aws-credentials action isn't required, but it may
      # give us more flexability going forward
      - name: Configure AWS Credentials
        if: contains(github.event.pull_request.labels.*.name, 'deploy')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Serverless Deploy
        id: serverless_deploy # is this needed?
        if: contains(github.event.pull_request.labels.*.name, 'deploy')
        run: npm run deploy